### ISSUE TITLE
Object converted in non-standard crs

### ISSUE THREAD

**Issue by GCOGit** [chris48s/arcgis2geojson#10]
ArcGIS online data appears to default to WKID 102100 CRS. GeoJSON coordinates are supposed to be in lat/long, and anything else seems to violate the standard. I haven't yet found a simple way to convert before feeding to arcgis2geojson, or having arcgis2geojson do it.

_The coordinate reference system for all GeoJSON coordinates is a
   geographic coordinate reference system, using the World Geodetic
   System 1984 (WGS 84) [WGS84] datum, with longitude and latitude units
   of decimal degrees._

WARNING:root:Object converted in non-standard crs - {'wkid': 102100}

`{"type": "Feature", "geometry": {"type": "Polygon", "coordinates": [[[-11788432, 4821816], [-11788404, 4821784], [-11788432, 4821816]]]}, "properties": null}
`

**Comment by chris48s** [comment]
RFC 7946 does state WGS 84 should be used and removes the CRS member of the 2008 standard, but it does include the caveat

> However, where all involved parties have a prior arrangement, alternative coordinate reference systems can be used without risk of data being misinterpreted.

so a GeoJSON file using a non-WGS84 CRS isn't strictly invalid. Refs

* https://tools.ietf.org/html/rfc7946#section-4
* https://tools.ietf.org/html/rfc7946#appendix-B.1

So this behaviour is intentional: We convert the file using the input CRS and emit a warning if its not 4326. It is out of scope for a simple format conversion tool to attempt to transpose between co-ordinate reference systems.

---

If you're looking for a way to emit ArcGIS JSON which isn't stored natively using WGS 84, your ArcGIS server can probably do it for you. If you're outputting from ArcGIS REST server, have a look at the `outSR` param. For example if I request:

https://ons-inspire.esriuk.com/arcgis/rest/services/Administrative_Boundaries/Combined_Authorities_December_2019_Boundaries_EN_BFE/MapServer/0/query?where=objectid%3D1&f=pjson

this outputs ArcGIS JSON using the server's default srid 27700, but if I append `&outSR=4326`

https://ons-inspire.esriuk.com/arcgis/rest/services/Administrative_Boundaries/Combined_Authorities_December_2019_Boundaries_EN_BFE/MapServer/0/query?where=objectid%3D1&f=pjson&outSR=4326

it will convert it to 4326 :tada:

**Comment by GCOGit** [comment]
Ah. Didn't see that exemption in the spec. Guess that's why ESRI's FeatureSet.to_GeoJSON preserves WKID 102100 and doesn't convert to WGS 84/4326. All I have access to is "item = gis.content.get(id)" (which returns "OperationalLayers"). I think a layer needs to be "published" for GeoJSON, etc. export options to appear. I didn't seem to see a way to do a REST query using an item id along with outSR.

I finally got a working Python script that converts the data to valid GeoJSON, also using json, pyproj, shapely, etc. libraries. Basically:

```
# EPSG:3857
# WGS 84 / Pseudo-Mercator -- Spherical Mercator, Google Maps, OpenStreetMap, Bing, ArcGIS, ESRI
# Alternatives codes : 900913 3587 54004 41001 102113 102100 3785
esriwgs = pyproj.CRS('EPSG:3857')
wgs84 = pyproj.CRS('EPSG:4326')
project = pyproj.Transformer.from_crs(esriwgs, wgs84, always_xy=True).transform

gis = GIS()
item = gis.content.get(id)
wm = WebMap(item)

for layer in wm.layers:
  fc = FeatureCollection(layer.featureCollection)
  fs = fc.query() # Only way to get a functional FeatureSet? This query apparently accepts no options.

  # print "type": "FeatureCollection", "features": [", etc.

  for feature in fs:
    # print "type": "Feature"...
    print('"properties": ' + json.dumps(feature.attributes))
    geom = arcgis.geometry.Geometry(feature.geometry)

    newgeom = transform(project, geom.as_shapely)
    print(', "geometry": ', geojson.dumps(newgeom))
```

I tried ArcGIS's "fc.query(out_sr=4326)" and "geom.project_as('EPSG:4326')" variations, but didn't seem to work. Anyway, I couldn't find any existing script or program out there that does this. Maybe I or somebody else could release one. :)

**Comment by chris48s** [comment]
Glad you managed to find a solution :+1:
