### ISSUE TITLE
Performance: Very large arcgis ring geometry (complex, many points) 

### ISSUE THREAD

**Issue by SmileSydney** [chris48s/arcgis2geojson#3]
@chris48s: Fantastic port!!! Thanks for this project!!

I'm retrieving feature data from a government ArcGIS-based REST service and then inserting into a postgis table. I'm converting Arcgis geometry to geojson using arcgis2geojson and then using geoalchemy2 to convert to native postgis geometry (I'm sure there's a better way...)

Anyway, some of the features from this source has geometry (rings) that is very complex i.e. has many points (in Notepad++ text editor, there is one feature where /feature/geometry/rings has almost 11million+ text columns!!). I know I need to simplify the geometry before insert into postgis but I think I need to convert it to something like geojson first. 

Any experience you could share on the below:
a) How I can simplify the esri arcgis geometry before running arcgis2geojson?
or
b) Ways to get arcgis2geojson to complete the operation on very complex arcgis geometry json faster? Do you know of data issues that could be fixed/removed in the source to improve performance?
or
c) Adding some print output to show progress of arcgis2geojson?

**Comment by chris48s** [comment]
The largest input files I've ever run through this myself are in the order of ~10Mb. It has always performed well enough for my purposes, but I'm open to feedback on how performance might be improved.

That said, if your objective is just to get data from a ArcGIS rest service into PostGIS, this may not be the best tool to help you. Converting to GeoJSON as an intermediate process is going to make your process slower rather than faster whichever way you slice it. Simplifying the geographies will be best done either in ArcGIS or PostGIS rather than when serialized as JSON.

However, I will see if I can provide a couple of tips:

1. I guess the first thing I'd suggest would be to see if you can get the ArcGIS server to do the work for you if possible. If you can have the service produce simplified outputs rather than producing complex outputs and having to simplify them yourself, that is going to help. Look into https://developers.arcgis.com/rest/services-reference/simplify.htm or https://developers.arcgis.com/rest/services-reference/generalize.htm

2. The other question I'd ask is can you break the problem down at all? If you've got one very large detailed polygon you won't be able to, but if you've got a large FeatureCollection composed of lots of polygons, you could request it in chunks from the web service. (e.g: by calling `/query?where=objectid%3D1`, `/query?where=objectid%3D2`.. or something) to give you smaller files that are easier to deal with one-by-one.

Best of luck with your project. If you can provide more specific feedback on performance problems with this package or more details/example of an input that results in performance issues, feel free to add it to this thread.

**Comment by SmileSydney** [comment]
Thanks for your response.

The only publicly available service that I'm aware on this government source is the query feature service layer (https://developers.arcgis.com/rest/services-reference/query-feature-service-layer-.htm). I can possibly reduce the geometry precision via this query (via parameter) but doesn't appear I can simplify. Geometry utilities don't appear to be accessible either.

I am only selecting 100 object IDs at a time and there are single objects that have 10mil column geometry json!

May be I am doing unnecessary steps cos I don't know any better. Here's what I'm doing
ArcGIS REST query feature service layer -> esri json -> arcgis2geojson -> convert to shape (using Shapely library) -> geoalchemy shape -> insert into table.

I think there is a ArcPy library function called AsShape which can take esri json or geojson and convert it to a shape suitable for geoalchemy. But this requires ArcGIS Desktop which I don't have.

Could you recommend a better way? I can probably do this in ogr2ogr.exe but I want to stay in Python.

Thanks

**Comment by chris48s** [comment]
Many older versions of ArcGIS REST Services support exporting as KML or KMZ (KMZ is basically a KML in a zip file) which can be loaded directly into PostGIS using `ogr2ogr` - see https://github.com/martindotlindner/carsharing/wiki/Import-kml-into-a-PostGIS-Database for an example.

Additionally, as noted in the documentation link you posted, newer versions of ArcGIS REST Services support exporting directly in GeoJSON format ( using `?f=geojson` ). GeoJSON can also be imported directly into PostGIS using `ogr2ogr`.

If either of those are an option, either of those are likely to be a much faster option than performing multiple intermediate format conversions.

I'm not familiar with GeoAlchemy so I can't offer you any advice on that. You might also want to consider posting on https://gis.stackexchange.com/ where a larger audience may be able to help you.

**Comment by SmileSydney** [comment]
Thanks @chris48s - you've been a great help!

**Comment by SmileSydney** [comment]
I actually didn't see the f=geojson before! One of my govt sources is on an older version doesn't support this so I forgot about it but the other one - the one with the enormous geometry - does support it! So thanks again!

**Comment by chris48s** [comment]
:smile: :tada:
